### ISSUE TITLE
Switch to another test-rpc tool for running tests

### ISSUE THREAD

**Issue by alisinabh** [ExWeb3/elixir_ethers#104]
Ganache-cli is [deprecated and sunset](https://github.com/trufflesuite/ganache).

We have the following candidates for replacement:

- [anvil](https://github.com/foundry-rs/foundry/tree/master/crates/anvil)
  - Requires changes to tests as deployments are not instant.
  - signing a transaction is not supported.
- [hardhat](https://hardhat.org/) nodes.

**Comment by alisinabh** [comment]
Current issues with anvil:

- `eth_signTransaction` is not behaving as expected (Fix pending in https://github.com/foundry-rs/foundry/pull/7804)
- There is a delay after a transaction is received by anvil until it is part of the next block. Doing a quick lookup after `eth_sendTransaction` to get the transaction receipt will result in a transaction not found error.

**Comment by BlazeWasHere** [comment]
>     * There is a delay after a transaction is received by anvil until it is part of the next block. Doing a quick lookup after `eth_sendTransaction` to get the transaction receipt will result in a transaction not found error.

btw the default action in anvil is to do "interval mining", to disable this use `--no-mining`

```sh
$ anvil
[...]
      --no-mining
          Disable auto and interval mining, and mine on demand instead
          
          [aliases: no-mine]
[...]
```

**Comment by alisinabh** [comment]
@BlazeWasHere Thanks for the info. I think I tested the --no-mining switch and what it does is that it requires you to explicitly call the mine function every time you want to mine a new block.

Actually I now realize my description of this issue is also wrong. This issue only seems to occur for transactions which are deploying a new contract. Other transactions are mined instantly.

**Comment by BlazeWasHere** [comment]
> @BlazeWasHere Thanks for the info. I think I tested the --no-mining switch and what it does is that it requires you to explicitly call the mine function every time you want to mine a new block.
> 
> Actually I now realize my description of this issue is also wrong. This issue only seems to occur for transactions which are deploying a new contract. Other transactions are mined instantly.

whoops i gave the wrong info there (sorry was late at night)... the default action is to auto mine (on new transaction sent) not interval mining, and yes `--no-mining` required calling `evm_mine`

![image](https://github.com/ExWeb3/elixir_ethers/assets/69124640/cbd6a920-178e-4888-b071-43a4d5178053)

> Actually I now realize my description of this issue is also wrong. This issue only seems to occur for transactions which are deploying a new contract. Other transactions are mined instantly.

i think the issue is down to how quick the local network is, `Ethers.deployed_address/2` does a one-shot query of `eth_getTransactionReceipt` however, due to `anvil` being ran locally, the query is ran before the block has been mined by the background miner thread. albeit slightly misleading, auto mining does not block `eth_sendTransaction` to mine a new block, instead the miner thread mines as soon as it receives the new transaction.

this can be confirmed on linux using netem (or just run anvil on a remote server)
```sh
# adds a 1ms delay to all outbound packets on loopback interface `lo`
$ tc qdisc add dev lo root netem delay 1ms
$ anvil &
$ mix test
# remove the delay made above
$ tc qdisc del dev lo root
```

i guess a solution is to poll and wait for `eth_getTransactionReceipt` to return the transaction receipt?

**Comment by alisinabh** [comment]
That seems like a good explanation. We did not have these issues with ganache probably because it is single threaded and we can be sure that a block was mined when we get a response back from send transaction.

> i guess a solution is to poll and wait for eth_getTransactionReceipt to return the transaction receipt?
ethersjs has [provider.waitForTransaction()](https://docs.ethers.org/v5/api/providers/provider/#Provider-waitForTransaction) and [transaction.wait()](https://docs.ethers.org/v5/api/providers/types/#providers-TransactionResponse)

Yes, if not in the lib itself, we need something like this (probably using Process.sleep as we don't have websockets) to wait for transactions to be mined in tests. This can especially become a problem in CI where resources are very limited and we might start seeing random failures (flakey tests).
